# Exploratory Data Analysis: Carbon (CO2) Emissions by Country
This notebook performs basic EDA on the carbon emissions dataset.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('../datasets/3_carbon_emission_and_sustainable_energy/Carbon_(CO2)_Emissions_by_Country.csv')
df.head()

       Country Region        Date  Kilotons of Co2  Metric Tons Per Capita
0  Afghanistan   Asia  01-01-2011           8930.0                    0.31
1  Afghanistan   Asia  01-01-2012           8080.0                    0.27
2  Afghanistan   Asia  01-01-2010           7110.0                    0.25
3  Afghanistan   Asia  01-01-2019           6080.0                    0.16
4  Afghanistan   Asia  01-01-2018           6070.0                    0.17

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5677 entries, 0 to 5676
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country                 5677 non-null   object
 1   Region                  5677 non-null   object
 2   Date                    5677 non-null   object
 3   Kilotons of Co2         5677 non-null   float64
 4   Metric Tons Per Capita  5677 non-null   float64
dtypes: float64(2), object(3)
memory usage: 221.9+ KB

In [3]:
df.describe()

       Kilotons of Co2  Metric Tons Per Capita
count     5.677000e+03             5677.000000
mean      1.412292e+05                4.325505
std       6.491258e+05                5.503834
min       0.000000e+00                0.000000
25%       1.380000e+03                0.570000
50%       9.170000e+03                2.360000
75%       5.848000e+04                6.340000
max       1.070722e+07               47.650000